title: "Winfried Ripken"
description: "PhD student in machine learning for the natural sciences"
url: "https://winfried-ripken.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty

author:
  name: "Winfried Ripken"
  role: "PhD Student"
  affiliation: "TU Berlin / BIFOLD"
  location: "Berlin, Germany"
  email: ""
  github: "winfried-ripken"
  twitter: "RipkenWinfried"
  scholar_url: "https://scholar.google.com/citations?user=wAVKdLcAAAAJ&hl=en&oi=ao"

scholar:
  user_id: "wAVKdLcAAAAJ"

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - scripts
  - .github
